command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - 8000
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "148ccb90800933a1"
  - name: LAKEBASE_DB
    value: "airlines-pre-flight"
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "148ccb90800933a1"
      permission: CAN_USE
  - name: serving-endpoint
    serving_endpoint:
      name: "databricks-meta-llama-3-3-70b-instruct"
      permission: CAN_QUERY
  - name: postgres
    lakebase:
      name: "airlines-pre-flight"
      permission: READ_WRITE
